@startuml
abstract class NotifyPropertyChanged {
    +  <<event>> PropertyChanged : PropertyChangedEventHandler? 
}
Disposable <|-- NotifyPropertyChanged
INotifyPropertyChanged <|-- NotifyPropertyChanged
@enduml
