@startuml
class ConfigurationAttribute <<sealed>> {
    + ConfigurationAttribute()
    + DefaultValue : object? <<get>> <<set>>
}
Attribute <|-- ConfigurationAttribute
ConfigurationAttribute --> "Persistence" ConfigurationPersistenceActions
@enduml
