name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}

    - name: Report build number
      run: echo "Build number is $BUILD_NUMBER"

    - name: Build with dotnet
      run: dotnet build --configuration Release -p:Version=$BUILD_NUMBER
      
    - name: Commit files
      run: |
        git config --local user.email "jevans@open-collar.org.uk"
        git config --local user.name "Jonathan Evans"
        git commit -m "Published documentation from source code." -a
      
    - name: Publish documentation
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
