name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Generate revision number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}
    
    - name: Generate version number
      run: |
        VERSION_REVISION=$BUILD_NUMBER
        echo "$VERSION_REVISION" > .version/revision.txt
        VERSION_MAJOR=$(<.version/major.txt)
        VERSION_MINOR=$(<.version/minor.txt)
        echo "$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION" > .version/version.txt
        VERSION=$(<.version/version.txt)
        echo "::set-env VERSION_MAJOR=$VERSION_MAJOR"
        echo "::set-env VERSION_MINOR=$VERSION_MINOR"
        echo "::set-env VERSION_REVISION=$VERSION_REVISION"
        echo "::set-env VERSION=$VERSION"
        echo "Version: $VERSION"

    - name: Build with dotnet
      run: |
        VERSION=$(<.version/version.txt)
        dotnet build --configuration Release -p:Version="$VERSION"

    -name: Set documentation version number
     run: |
        cd /docs
        grep -rli '[[VERSION]]' * | xargs -i@ sed -i 's/[[VERSION]]/$VERSION/g' @
      
    - name: Commit files
      run: |
        git config --local user.email "jevans@open-collar.org.uk"
        git config --local user.name "Jonathan Evans"
        git commit -m "Published documentation from source code." -a
      
    - name: Publish documentation
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
